### ISSUE TITLE
Embed blocks not displayed correctly

### ISSUE THREAD

**Issue by huegerich** [tombarys/roam-depot-nautilus#2]
<img width="119" alt="image" src="https://github.com/tombarys/roam-depot-nautilus/assets/6596076/bf9bf5a1-5211-4798-828a-3179c390f125">

Here's how the embedded block looks in my task list:
<img width="121" alt="image" src="https://github.com/tombarys/roam-depot-nautilus/assets/6596076/15e5c355-378d-44b7-8fbe-ffc0f2d8406d">
(The code for it is `{{embed: ((5LzbLa2SC))}}`)

I expected the label in the visual to just say "Chat with Sherry re"

Thanks! I feel like this is already really helping me.

**Comment by tombarys** [comment]
Dear Tim, you are right, the extension does not parse embedded blocks yet. I will put it on my list and will tack it later. Thank you for your kind words and feedback!

**Comment by tombarys** [comment]
Dear Tim, if you know how to enable developer mode in Roam Depot, you can start testing new version that removes these embed chunks. Just remove the running extension (via Roam Depot uninstall), switch on dev mode in Roam Depot main screen, click on the chain icon in Roam Depot store and put `tombarys+nautilus+836` instead of URL in the input box. Enter.

**Comment by tombarys** [comment]
Updated in the production version in Roam Depot. Just update :)
